//
//  ContentViewModelTest.swift
//  XCTestSampleTests
//
//  Created by 佐藤汰一 on 2025/03/01.
//

import XCTest

@testable import SwiftTestingSample

final class ContentViewModelTest: XCTestCase {

    func test_画面表示時にタイトルとメッセージを表示する() {
        
        let viewModel = ContentViewModel()
        
        viewModel.onAppear()
        
        let expected = ContentViewModel()
        expected.title = "Hello World!!"
        expected.message = "Generated by objective-c message!"
        XCTAssertEqual(viewModel, expected)
    }
    
    func test_ボタンをタップするとタイトルを更新する() {
        
        let viewModel = ContentViewModel()
        
        viewModel.tappedButton()
        
        let expected = ContentViewModel()
        expected.title = "Hello World!!"
        expected.message = "Generated by objective-c message!"
        XCTAssertEqual(viewModel, expected)
    }
}
