//
//  MessageGeneratorTest.swift
//  XCTestSampleTests
//
//  Created by 佐藤汰一 on 2025/03/02.
//

import XCTest

@testable import SwiftTestingSample

final class MessageGeneratorTest: XCTestCase {

    func test_メッセージを返す() {
        
        guard let message = MessageGenerator().getMessage() else {
            
            XCTFail()
            return
        }
        
        XCTAssertEqual(message, "Generated by objective-c message!")
    }
}
