//
//  MessageGenerator.m
//  SwiftTestingSample
//
//  Created by 佐藤汰一 on 2025/03/01.
//

#import "SwiftTestingSample-Bridging-Header.h"

@implementation MessageGenerator

- (NSString *)getMessage {
    return @"Generated by objective-c message!";
}

@end

